config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  
  devise_for :users, :path=>"auth", :controllers=>{:registrations => :users}
  
  resources :users
  resources :grades, only: [:update, :edit, :show]
  resources :students do
    collection do
      post 'bulk_add'
      post 'bulk_remove'
    end
  end
  resources :assignments do
    member do
      get 'edit_grades'
      get 'update_grades'
      post 'save_grades'
    end
  end

  get 'admin/index' => 'admin#index'
  get 'reports/students' => 'reports#students'
  get 'reports/master' => 'reports#master'
  
  resources :lockers do
    collection do
      get 'checkout'
      post 'bulk_update'
      put 'rotate'
    end
  end
  
  resources :items

end

app/models/assignment.rb
class Assignment < ApplicationRecord
 #---Associations-----
  has_many :grades, dependent: :destroy
  has_many :students, -> { distinct }, through: :grades
   
  #---Attributes------
  #  name (string)
  #  description (string)
  #  abbreviation (string)
  #  value (boolean)
  
  
  #---Validations------
  validates :name, :presence=> true, :uniqueness=>true
  validates :abbreviation, :presence=> true, :uniqueness=>true
  validates :value, numericality: {greater_than: 0}
  #---Class Methods----
  
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_assignment, only: [:show, :edit, :update, :destroy, 
        :edit_grades, :update_grades, :save_grades]
  
    # GET /assignment
    # GET /assignments.json
    def index
      @assignments = Assignment.all
    end
  
    # GET /assignments/1
    # GET /assignments/1.json
    def show
      respond_to do |format|
        format.html
        format.pdf do
          render :pdf => "show.html.erb"
        end
      end
    end
  
    # GET /assignments/new
    def new
      @assignment = Assignment.new
    end
  
    # GET /assignments/1/edit
    def edit
    end
  
    # GET /assignments/1/edit_grades
    def edit_grades
      respond_to do |format|
        format.html {render :edit_grades}
        format.pdf { render :layout=>'latex', formats: [:pdf]}
      end
    end
    
    # GET /assignments/1/update_grades
    def update_grades
      respond_to do |format|
        format.html {render :update_grades}
        format.pdf { render :layout=>'latex', formats: [:pdf]}
      end
    end
    
    # POST /assignments/1/save_grades
    def save_grades
      grade_data = params[:grades]
      grade_data.each do |id,value|
        grade = Grade.find(id)
        grade.value = value
        grade.save!
      end
      flash.notice = 'Assignment successfully updated'
      flash.keep(:notice)
      render plain: "ok"
    end
    
    # POST /assignments
    # POST /assignments.json
    def create
      unless current_user.admin?
        render nothing: true, status: :unauthorized and return
      end
      @assignment = Assignment.new(assignment_params)
      @assignment.save
      Grade.build_all
      respond_to do |format|
        if @assignment.valid?
          format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
          format.json { render :show, status: :created, location: @assignment }
        else
          format.html { render :new }
          format.json { render json: @assignment.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /assignments/1
    # PATCH/PUT /assignments/1.json
    def update
      unless current_user.admin?
        render nothing: true, status: :unauthorized and return
      end
      respond_to do |format|
        if @assignment.update(assignment_params)
          format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
          format.json { render :show, status: :ok, location: @assignment }
        else
          format.html { render :edit }
          format.json { render json: @assignment.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /assignments/1
    # DELETE /assignments/1.json
    def destroy
      unless current_user.admin?
        render nothing: true, status: :unauthorized and return
      end
      @assignment.destroy
      Grade.build_all
      respond_to do |format|
        format.html { redirect_to assignments_url, notice: 'Assignment was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
    
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_assignment
        @assignment = Assignment.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def assignment_params
        params.require(:assignment).permit(:name, :description, :value, :abbreviation)
      end
  end
  

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div class="alert alert-danger">
      <h3><%= pluralize(@assignment.errors.count, "error") %> 
        prohibited this assignment from being saved:</h3>
      <ul>
      <% @assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% form_class="form-group"%>
  <% form_class+=" has-error" if @assignment.errors.include?(:name)%>
  <div class="<%=form_class%>">
    <%= f.label :name, :class=>"control-label"%>
    <%= f.text_field :name, :class=>"form-control"%>
  </div>
  <% form_class="form-group"%>
  <% form_class+=" has-error" if @assignment.errors.include?(:abbreviation)%>
  <div class="<%= form_class%>">
    <%= f.label :abbreviation, :class=>"control-label"%>
    <%= f.text_field :abbreviation, :class=>"form-control" %>
  </div>
  <% form_class="form-group"%>
  <% form_class+=" has-error" if @assignment.errors.include?(:description)%>
  <div class="<%= form_class%>">
    <%= f.label :description, :class=>"control-label" %>
    <%= f.text_field :description, :class=>"form-control"  %>
  </div>
  <% form_class="form-group"%>
  <% form_class+=" has-error" if @assignment.errors.include?(:value)%>
  <div class="<%= form_class%>">
    <%= f.label :value, :class=>"control-label"%>
    <%= f.text_field :value, :class=>"form-control"  %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class=>"btn btn-primary"%>
    <%if @assignment.id==nil%>
      <%cancel_path=assignments_path%>
    <%else %>
      <%cancel_path=assignment_path(@assignment)%>
    <%end%>
    <a href="<%=cancel_path%>" class="btn btn-default">Cancel</a>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h2>Editing Assignment</h2>

<%= render 'form' %>
<%= button_to "Delete Assignment", @assignment, :method => :delete, :class => "btn btn-danger pull-right" %>

app/views/assignments/edit_grades.html.erb
<h2>Enter Grades for <%=@assignment.name%>
<a class="btn btn-primary pull-right"
  href="<%=edit_grades_assignment_path(@assignment)%>.pdf"> <i class="fa fa-print"></i>  Print This Page</a></h2>

<table class="table">
  <thead>
    <th>Student</th>
    <th>Grade</th>
  </thead>
  <tbody>
  <!--sort by last name-->
  <%@assignment.grades.includes(:student).order('students.last_name').each do |grade|%>
    <tr>
      <td><%=grade.student.full_name%></td>
      <td>
        <input type="text" class="jsGrade form-control" data-id="<%=grade.id%>" 
          placeholder="0"  value="<%=grade.value%>">
      </td>
    </tr>
  <%end%>
  </tbody>
</table>
<%if current_user.admin?%>
<a type="button" class="btn btn-primary disabled" id="btnSaveGrades"><i class="icon-plus"></i> Save Grades</a>

<%end%>
<a href="<%=assignment_path(@assignment)%>" class="btn btn-default">Back</a>

<script>
$(function(){
  $("#btnSaveGrades").click(function(){
    if(validateAll()==false)
      return;
    var grades = {};
    //build a tuples of all the grades
    $(".jsGrade").each(function(index){
      var id = parseInt($(this).attr("data-id"));
      var grade = 0
      if($(this).val()!="")
        grade = parseFloat($(this).val());
      grades[id]=grade;
    });
    //now we have validated grades, send to server
    $.ajax({
      type: "POST",
      url: "<%=save_grades_assignment_path(@assignment)%>",
      data: {"grades":grades},
      success: saveComplete,
    });
  });
  //input validation 
  $(".jsGrade").change(function(){
    var input = $(this).val();
    if(input=="")
      return;
    //if the grade text is not a number, highlight the row
    if(isNaN(parseFloat(input)) || parseFloat(input)<0){
      $(this).parent().parent().addClass("danger");
    } else {
      $(this).parent().parent().removeClass("danger");
    }
    //now validate the rest of the inputs to see if we can save
    validateAll();
  });
  //save is complete, redirect the user to the assignments page
  function saveComplete(){
    window.location="<%=assignment_path(@assignment)%>"
  }
  //only enable button when all inputs are valid
  function validateInput(x){
    if(x=="")
      return true;
    if(isNaN(parseFloat(x)) || parseFloat(x)<0)
      return false;
    return true;
  };
  //check all inputs to make sure they are valid
  function validateAll(){
    isValid=true;
    $(".jsGrade").each(function(index){
      if(validateInput($(this).val())==false){
        isValid=false;
      }
    });
    if(isValid){
      $("#btnSaveGrades").removeClass("disabled");
    } else {
      $("#btnSaveGrades").addClass("disabled");
    }
    return isValid;
  };
});
</script>

app/views/assignments/edit_grades.pdf.erb
\begin{centering}

\vspace*{2mm}



\textbf{\LARGE <%=lesc(@assignment.name)%> Grades}{\LARGE \par}
\today


\vspace{1cm}

\rowcolors{1}{white}{lightgray}

\newcolumntype{R}{>{\centering\arraybackslash}X}
\renewcommand{\arraystretch}{1.3}
\begin{tblr}{r|l|l|l|r}
\textbf{Name}&\textbf{Athena}&\textbf{Grade}&\textbf{Staff Initial}&\textbf{Notes}\\ \hline\hline

<%@assignment.grades.includes(:student).order('students.last_name').each do |grade|%>
<%=lesc(grade.student.full_name)%>&<%=lesc(grade.student.athena)%>&&&\\ \hline
<%end-%>
\end{tblr}

\end{centering}

app/views/assignments/index.html.erb
  <h2>Assignments</h2>
  <table class="table">
    <thead>
        <th>Name</th>
        <th>Description</th>
        <th>Value</th>
    </thead>
    <tbody>
      <%@assignments.each do |assignment|%>
      <tr>
        <td><%=link_to assignment.name, assignment_path(assignment)%></td>
        <td>
          <%=assignment.description%>
        </td>
        <td>
          <%=assignment.value%>
        </td>
      </tr>
      <%end%>
    </tbody>
  </table>
  <% if current_user.admin?%>
  <a type="button" class="btn btn-primary"
    href="<%=new_assignment_path%>"><i class="icon-plus"></i> Add Assignment</a>
  <%end%>
  <a type="button" class="btn btn-default" href="<%=root_path%>">Back</a>

app/views/assignments/new.html.erb
<h2>New Assignment</h2>

<%= render 'form' %>

app/views/assignments/show.html.erb
<h2>Assignment: <%=@assignment.name%></h2>

<div class="row">
  <div class="col-md-6">
    <dl class="dl-horizontal">
      <dt>Abbreviation</dt><dd><%=@assignment.abbreviation%></dd>
      <dt>Description</dt><dd><%=@assignment.description%></dd>
      <dt>Value</dt><dd><%=@assignment.value%></dd>
    </dl>
  </div>
  <div class="col-md-6">
    <a type="button" class="btn btn-primary" 
      href="<%=edit_grades_assignment_path(@assignment)%>">Enter Grades</a>
    <span class="lead">|</span>
    <a type="button" class="btn btn-primary"
      href="<%=update_grades_assignment_path(@assignment)%>">Update Grades</a>
  </div>
</div>
<table class="table">
  <thead>
    <th>Student</th>
    <th>Grade</th>
    <th></th>
  </thead>
  <tbody>
  <!--sort by last name-->
  <%@assignment.grades.includes(:student).order('students.last_name').each do |grade|%>
    <tr>
      <td><%=grade.student.full_name%></td>
      <td>
        <%if grade.value==nil%>
          &mdash;
        <%else%>
          <%=number_to_human(grade.value, precision: 4, strip_insignificant_zeros: true)%>
        <%end%>
      </td>
      <td>
        <a href="<%=edit_grade_path(grade)%>">
          <i class="fa fa-edit"></i></a>
      </td>
    </tr>
  <%end%>
  </tbody>
</table>
<%if current_user.admin?%>
<a type="button" class="btn btn-primary"
  href="<%=edit_assignment_path(@assignment)%>"><i class="icon-plus"></i> Edit Assignment</a>

<%end%>
<a href="<%=assignments_path%>" class="btn btn-default">Back</a>

app/views/assignments/update_grades.html.erb
<h2>Update Grades for <%=@assignment.name%>
  <a class="btn btn-primary pull-right"
    href="<%=update_grades_assignment_path(@assignment)%>.pdf">
    <i class="fa fa-print"></i>  Print This Page</a>
</h2>

<table class="table">
  <thead>
    <th>Student</th>
    <th>Grade</th>
  </thead>
  <tbody ng-controller="GradeCtrl">
  <!--sort by last name-->
  <%@assignment.grades.includes(:student).order('students.last_name').each do |grade|%>
    <tr>
      <td><%=grade.student.full_name%></td>
      <td>
        <form class="form-inline"> <%grade.value = 0 if grade.value==nil%>
        <%=number_to_human(grade.value, precision: 4, strip_insignificant_zeros: true)%>
        + <input type="text_field" class="grade_txt form-control jsGrade" 
          data-id="<%=grade.id%>" data-grade="<%=grade.value%>"
          placeholder="0" ng-model="ng<%=grade.id%>" > = 
          <strong>{{sum(<%=grade.value%>,ng<%=grade.id%>)}}</strong>
        </form>
      </td>
    </tr>
  <%end%>
  </tbody>
</table>
<%if current_user.admin?%>
<a type="button" class="btn btn-primary disabled" id="btnSaveGrades"><i class="icon-plus"></i> Save Grades</a>

<%end%>
<a href="<%=assignment_path(@assignment)%>" class="btn btn-default">Back</a>

<script>
$(function(){
  $("#btnSaveGrades").click(function(){
    if(validateAll()==false)
      return;
    var grades = {};
    //build a tuples of all the grades
    $(".jsGrade").each(function(index){
      var id = parseInt($(this).attr("data-id"));
      var grade = parseFloat($(this).attr("data-grade"));
      if(isNaN(grade)) //updating a nil grade
        grade = 0;
      if($(this).val()!="")
        grade += parseFloat($(this).val());
      grades[id]=grade;
    });
    //now we have validated grades, send to server
    $.ajax({
      type: "POST",
      url: "<%=save_grades_assignment_path(@assignment)%>",
      data: {"grades":grades},
      success: saveComplete,
    });
  });
  //input validation 
  $(".jsGrade").change(function(){
    var input = $(this).val();
    if(input=="")
      return;
    //if the grade text is not a number, highlight the row
    if(isNaN(parseFloat(input)) || parseFloat(input)<0){
      $(this).parent().parent().parent().addClass("danger");
    } else {
      $(this).parent().parent().parent().removeClass("danger");
    }
    //now validate the rest of the inputs to see if we can save
    validateAll();
  });
  //save is complete, redirect the user to the assignments page
  function saveComplete(){
    window.location="<%=assignment_path(@assignment)%>"
  }
  //only enable button when all inputs are valid
  function validateInput(x){
    if(x=="")
      return true;
    if(isNaN(parseFloat(x)) || parseFloat(x)<0)
      return false;
    return true;
  };
  //check all inputs to make sure they are valid
  function validateAll(){
    isValid=true;
    $(".jsGrade").each(function(index){
      if(validateInput($(this).val())==false){
        isValid=false;
      }
    });
    if(isValid){
      $("#btnSaveGrades").removeClass("disabled");
    } else {
      $("#btnSaveGrades").addClass("disabled");
    }
    return isValid;
  };
});
</script>

app/views/assignments/update_grades.pdf.erb
\begin{center}

\vspace*{2mm}



\textbf{\LARGE Update <%=lesc(@assignment.name)%> Grades}{\LARGE \par}
\today


\vspace{1cm}

\rowcolors{1}{white}{lightgray}

\newcolumntype{C}{>{\centering\arraybackslash}X}
\renewcommand{\arraystretch}{1.3}
\begin{longtabu}{r|l|c|c|c|C}
\textbf{Name}&\textbf{Athena}&\textbf{Grade}&\textbf{Update}&\textbf{Staff Initial}&\textbf{Notes}\\ \hline\hline
<%@assignment.grades.includes(:student).order('students.last_name').each do |grade|%>
<%=lesc(grade.student.full_name)%>&<%=lesc(grade.student.athena)%>&<%=print_value(grade.value)%>&&&\\ \hline
<%end-%>
\end{longtabu}

\end{center}