config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  
  devise_for :users, :path=>"auth", :controllers=>{:registrations => :users}
  
  resources :users
  resources :grades, only: [:update, :edit, :show]
  resources :students do
    collection do
      post 'bulk_add'
      post 'bulk_remove'
    end
  end
  resources :assignments do
    member do
      get 'edit_grades'
      get 'update_grades'
      post 'save_grades'
    end
  end

  get 'admin/index' => 'admin#index'
  get 'reports/students' => 'reports#students'
  get 'reports/master' => 'reports#master'
  
  resources :lockers do
    collection do
      get 'checkout'
      post 'bulk_update'
      put 'rotate'
    end
  end
  
  resources :items

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, :presence=> true, :uniqueness=>true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user, only: [:show, :edit, :update, :destroy]
  
    # GET /users
    # GET /users.json
    def index
      @users = User.all
    end
  
    # GET /users/1
    # GET /users/1.json
    def show
    end
  
    # GET /users/new
    def new
      @user = User.new
    end
  
    # GET /users/1/edit
    def edit
    end
  
    # POST /users
    # POST /users.json
    def create
      #only admins can create users
      unless current_user.admin?
        render nothing: true, status: :unauthorized and return
      end
      @user = User.new(user_params)
      @user.admin=true if(params[:user][:admin]=="1")
      respond_to do |format|
        if @user.save
          format.html { redirect_to :users, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /users/1
    # PATCH/PUT /users/1.json
    def update
      #admins can change any account and users can change their own account
      unless current_user.admin? or @user.id==current_user.id
        render nothing: true, status: :unauthorized and return
      end
      #don't require the user to change password
      if user_params[:password]=="" and user_params[:password_confirmation]==""
        filtered_params=user_params.except(:password,:password_confirmation)
      else
        filtered_params=user_params
      end
      #only an admin can change 'admin' status, and can't change his own status
      if current_user.admin? and @user.id != current_user.id
        @user.admin= (params[:user][:admin]=="1" ? true : false)
      end
      respond_to do |format|
        if @user.update(filtered_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /users/1
    # DELETE /users/1.json
    def destroy
      #only admins can remove users. can't remove yourself
      if (not current_user.admin?) or (@user.id == current_user.id)
        render nothing: true, status: :unauthorized and return
      end
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
    
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
      end
  end
  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <h3><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% form_class="form-group"%>
  <% form_class+=" has-error" if @user.errors.include?(:username)%>
  <div class="<%=form_class%>">
    <%= f.label :username, :class=>"control-label"%>
    <%= f.text_field :username, :class=>"form-control"%>
  </div>
  <% form_class="form-group"%>
  <% form_class+=" has-error" if @user.errors.include?(:email)%>
  <div class="<%= form_class%>">
    <%= f.label :email, :class=>"control-label"%>
    <%= f.text_field :email, :class=>"form-control" %>
  </div>
  <% form_class="form-group"%>
  <% form_class+=" has-error" if @user.errors.include?(:password)%>
  <div class="<%= form_class%>">
    <%= f.label :password, :class=>"control-label" %>
    <%= f.password_field :password, :class=>"form-control"  %>
  </div>
  <% form_class="form-group"%>
  <% form_class+=" has-error" if @user.errors.include?(:password_confirmation)%>
  <div class="<%= form_class%>">
    <%= f.label :password_confirmation, :class=>"control-label"%>
    <%= f.password_field :password_confirmation, :class=>"form-control"  %>
  </div>
  <%if current_user.admin? and current_user!=@user%>
  <div class="checkbox">
     <label>
       <%= f.check_box :admin%> Admin
     </label>
   </div>
  <%end-%>
  <div class="actions">
    <%= f.submit 'Submit', :class=>"btn btn-primary"%>
    <a href="<%=users_path%>" class="btn btn-default">Cancel</a>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2>Editing User</h2>

<%= render 'form' %>

app/views/users/index.html.erb
  <h2>Users</h2>
  <table class="table">
    <thead>
        <th>Username</th>
        <th>Sign In Count</th>
        <th>Last Sign In</th>
        <th>Last IP</th>
        <th>Admin</th>
    </thead>
    <tbody>
      <%@users.each do |user|%>
      <tr class="clickable">
        <td><%=link_to user.username, user_path(user)%></td>
        <td><%=user.sign_in_count%></td>
        <td>
          <% if user.last_sign_in_at.blank?%>
            &mdash;
          <% else %>
            <span data-toggle="tooltip" data-placement="bottom" title="<%=user.last_sign_in_at%>">
              <%=time_ago_in_words(user.last_sign_in_at)+" ago"%>
            </span>
          <%end%>
        </td>
        <td>
          <% if user.last_sign_in_ip.blank?%>
            &mdash;
          <% else %>
            <%=user.last_sign_in_ip%>
          <%end%>
        </td>
        <td><% if user.admin?%>
            <i class="fa fa-check"></i>
            <%end%>
        </td>
        <td>
          <%if user!=current_user%>
          <a data-confirm="Are you sure?" data-method="delete" 
            href="<%=user_path(user)%>" rel="nofollow">
          <i class="fa fa-trash clickable"></i></a>
          <%end%>
        </td>
      </tr>
      <%end%>
    </tbody>
  </table>
  
  <a type="button" class="btn btn-primary"
    href="<%=new_user_path%>"><i class="icon-plus"></i> Add User</a>
  <a type="button" class="btn btn-default" href="<%=admin_index_path%>">Back</a>

app/views/users/new.html.erb
<h2>New User</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<h2>User Details</h2>

<dl class="dl-horizontal">
  <dt>Username</dt><dd><%=@user.username%></dd>
  <dt>E-mail</dt><dd><%=mail_to @user.email%></dd>
  <dt>Sign In Count</dt><dd><%=@user.sign_in_count%></dd>
  <dt>Current Sign In</dt><dd><%=@user.current_sign_in_at%></dd>
  <dt>Current Sign In IP</dt><dd><%=@user.current_sign_in_ip%></dd>
  <dt>Last Sign In</dt><dd><%=@user.last_sign_in_at%></dd>
  <dt>Last Sign In IP</dt><dd><%=@user.last_sign_in_ip%></dd>
  <dt>Admin?</dt><dd><%=@user.admin?%></dd>
</dl>

<%if @user==current_user or current_user.admin?%>
<a type="button" class="btn btn-primary"
  href="<%=edit_user_path(@user)%>"><i class="icon-plus"></i> Edit User</a>

<%end%>
<a href="<%=users_path%>" class="btn btn-default">Back</a>