config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  
  devise_for :users, :path=>"auth", :controllers=>{:registrations => :users}
  
  resources :users
  resources :grades, only: [:update, :edit, :show]
  resources :students do
    collection do
      post 'bulk_add'
      post 'bulk_remove'
    end
  end
  resources :assignments do
    member do
      get 'edit_grades'
      get 'update_grades'
      post 'save_grades'
    end
  end

  get 'admin/index' => 'admin#index'
  get 'reports/students' => 'reports#students'
  get 'reports/master' => 'reports#master'
  
  resources :lockers do
    collection do
      get 'checkout'
      post 'bulk_update'
      put 'rotate'
    end
  end
  
  resources :items

end

app/models/locker.rb
class Locker < ApplicationRecord

  
  #---Attributes------
  #  number (string)
  #  notes (string)
  #  kit (integer)
  
  #---Validations------
  #the locker has the lock integrated with it- not a seperate model
  validates :number, :presence=> true, :uniqueness=>true
  validates :serial, :presence=> true, :uniqueness=>true
  validates :combo, :presence=>true
  #---Class Methods----
  
  
end

app/controllers/lockers_controller.rb
class LockersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_locker, only: [:show, :edit, :update, :destroy]
    respond_to :json, :html
  
    # GET /lockers
    # GET /lockers.json
    def index
      @lockers = Locker.all
      respond_to do |format|
        format.pdf {render :layout=>'latex_table', formats: [:pdf]}
        format.html { render :index}
        format.json {render json: @lockers}
      end
     # respond_with @lockers
    end
  
    # GET /lockers/1
    # GET /lockers/1.json
    def show
    end
  
    # GET /lockers/new
    def new
      @locker = Locker.new
    end
  
    # GET /lockers/1/edit
    def edit
    end
  
    # POST /lockers
    # POST /lockers.json
    def create
      @locker = Locker.new(locker_params)
  
      respond_to do |format|
        if @locker.save
          format.html { redirect_to @locker, notice: 'Locker was successfully created.' }
          format.json { render :show, status: :created, location: @locker }
        else
          format.html { render :new }
          format.json { render json: @locker.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /lockers/1
    # PATCH/PUT /lockers/1.json
    def update
      respond_to do |format|
        if @locker.update(locker_params)
          format.html { redirect_to @locker, notice: 'Locker was successfully updated.' }
          format.json { render :show, status: :ok, location: @locker }
        else
          format.html { render :edit }
          format.json { render json: @locker.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /lockers/1
    # DELETE /lockers/1.json
    def destroy
      @locker.destroy
      respond_to do |format|
        format.html { redirect_to lockers_url, notice: 'Locker was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
    
    
    # PUT /lockers/bulk_update.json
    def bulk_update
      Locker.destroy_all
      params[:lockers].each do |locker|
        l = Locker.new(locker.permit(:number, :serial, :kit, :comment, :combo, :notes))
        unless l.valid?
          render json: {locker: l, errors: l.errors.full_messages}, status: :bad_request
          return
        end
        l.save!
      end
      render json: Locker.all
    end
    
    # PUT /lockers/rotate.json
    def rotate
      #rotate all lockers up by 1
      lockers = Locker.all
      last_serial = lockers.last.serial
      last_combo = lockers.last.combo
      i=lockers.length-1
      while i>0
        lockers[i].update_attribute(:serial,lockers[i-1].serial)
        lockers[i].update_attribute(:combo,lockers[i-1].combo)
        i-=1
      end
      lockers[0].update_attribute(:serial, last_serial)
      lockers[0].update_attribute(:combo, last_combo)
      lockers.each do |locker|
        puts locker.combo
        #locker.save!
      end
      
      redirect_to :lockers, notice: 'Locks rotated by +1'
    end
    
    # GET /lockers/checkout
    def checkout
      @lockers = Locker.all
      @contents = Item.all
      render :layout=>'latex', formats: [:pdf]
    end
    
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_locker
        @locker = Locker.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def locker_params
        params.require(:locker).permit(:number, :serial, :kit, :comment, :combo, :notes)
      end
  end
  

app/helpers/lockers_helper.rb
module LockersHelper
end

app/views/lockers/checkout.pdf.erb
\renewcommand{\baselinestretch}{1}\selectfont

<% @lockers.each do |locker|%>
\vspace*{1.2cm}

\begin{center}\textbf{\LARGE <%=@settings[:name]%> Kit Checklist}\end{center}{\LARGE \par}

\begin{center}<%=@settings[:semester]%> \end{center}

If any of the equipment listed below is missing from your locker, you
need to tell one of the TAs during lab familiarizations.  You will be
held responsible for any missing equipment not reported to the TAs by
the end of the week.  Any missing equipment will be replaced by the
course TAs, not by the equipment desk workers.

\renewcommand{\baselinestretch}{2}\selectfont
\begin{table}[h!]
\begin{center}
\begin{tabular}{rl}

Locker Number: & \underline{\parbox{3.5in}{\textbf{<%=locker.number%>} \hspace*{\fill}}} \\
Lock Number: & \underline{\parbox{3.5in}{\textbf{<%=locker.serial%>} \hspace*{\fill}}} \\
Kit Number: & \underline{\parbox{3.5in}{\textbf{<%=locker.kit%>} \hspace*{\fill}}} \\
Locker Combo: & \underline{\parbox{3.5in}{\textbf{<%= locker.combo%>} \hspace*{\fill}}}
\end{tabular}
\end{center}
\end{table}

\begin{center}
\textit{You should find the following items in your locker:}
\end{center}

\renewcommand{\baselinestretch}{1.5}\selectfont
%\renewcommand{\thefootnote}{\fnsymbol{footnote}}
%\setcounter{footnote}{0}
\begin{center}\begin{tabular}{|c|l|}
\hline
Qty & Item\\
\hline \hline
<%@contents.each do |item|%>
<%=item.quantity%> & <%=item.name%> \\ \hline
<%end%>

\end{tabular}
\end{center}

\pagebreak
<%end%>

app/views/lockers/edit.html.erb
<h2>Editing Locker</h2>



<%= form_for(@locker) do |f| %>
  <% if @locker.errors.any? %>
    <div class="alert alert-danger">
      <h3><%= pluralize(@locker.errors.count, "error") %> prohibited this locker from being saved:</h3>

      <ul>
      <% @locker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% form_class="form-group"%>
  <% form_class+=" has-error" if @locker.errors.include?(:number)%>
  <div class="<%=form_class%>">
    <%= f.label :number, :class=>"control-label"%>
    <%= f.text_field :number, :class=>"form-control"%>
  </div>
  <% form_class="form-group"%>
  <% form_class+=" has-error" if @locker.errors.include?(:serial)%>
  <div class="<%=form_class%>">
    <%= f.label :serial, :class=>"control-label"%>
    <%= f.text_field :serial, :class=>"form-control"%>
  </div>
  <% form_class="form-group"%>
  <% form_class+=" has-error" if @locker.errors.include?(:combo)%>
  <div class="<%=form_class%>">
    <%= f.label :combo, :class=>"control-label"%>
    <%= f.text_field :combo, :class=>"form-control"%>
  </div>
  <% form_class="form-group"%>
  <% form_class+=" has-error" if @locker.errors.include?(:kit)%>
  <div class="<%=form_class%>">
    <%= f.label :kit, :class=>"control-label"%>
    <%= f.text_field :kit, :class=>"form-control"%>
  </div>
  <% form_class="form-group"%>
  <% form_class+=" has-error" if @locker.errors.include?(:notes)%>
  <div class="<%=form_class%>">
    <%= f.label :notes, :class=>"control-label"%>
    <%= f.text_field :notes, :class=>"form-control"%>
  </div>
  
  <div class="actions">
    <%= f.submit 'Save', :class=>"btn btn-primary"%>
    <a href="<%=lockers_path%>" class="btn btn-default">Cancel</a>
  </div>
<% end %>

app/views/lockers/index.html.erb
  <h2>Lockers</h2>
  <table class="table">
    <thead>
        <th>Number</th>
        <th>Lock</th>
        <th>Combo</th>
        <th>Kit</th>
        <th>Notes</th>
        <th></th>
    </thead>
    <tbody>
      <%@lockers.each do |locker|%>
      <tr>
        <td>
          <%=locker.number%>
        <td>
         <%=locker.serial%> 
        </td>
        <td>
          <%=locker.combo%>
        </td>
        <td>
          <%=locker.kit%>
        </td>
        <td>
          <%=locker.notes%>
        </td>
        <td>
          <a href="<%=locker_path(locker)%>"<i class="fa fa-edit"></i></a>
        </td>
        
      </tr>
      <%end%>
    </tbody>
  </table>
  <a type="button" class="btn btn-primary"
    href="<%=new_locker_path%>"><i class="icon-plus"></i> Edit</a>
  <a type="button" data-confirm="Are you sure?" data-method="put"
     class="btn btn-primary pull-right btn-danger" href="<%=rotate_lockers_path%>" rel="nofollow">
     <i class="fa fa-lock"></i>  Rotate Locks +1</a>
  <a type="button" class="btn btn-default" href="<%=admin_index_path%>">Back</a>

app/views/lockers/index.pdf.erb
List of Lockers

\begin{longtable}{r|l|l|l|l}
<%#Build the table header%>
\textbf{Locker}&\textbf{Serial}&\textbf{Combo}
&\textbf{Kit}&\textbf{Notes}
\\ \hhline{=====}
\endhead
<%@lockers.each do |locker|%>
  <%=locker.number%>&<%=locker.serial%>&<%=locker.combo-%>&
  <%=locker.kit%>&<%=locker.notes-%>
  
  \\ \hline
<%end-%>


\end{longtable}

app/views/lockers/new.html.erb
<div ng-controller="LockerCtrl" ng-init="init()">
  <h2>Setup Lockers</h2>
  Locker Number, Lock Serial, Lock Combo, Kit Number, Notes

  <hr>
  <form class="clearfix">
    <div class="form-group">
    <textarea ui-codemirror="editorOptions" 
      placeholder="23, 12345, 23-15-26 missing book" class="form-control" rows=10
       ng-model="bulk_input" ng-change="parseInput()"></textarea>
    </div>
    <div class="form-group">
      <span ng-show="syntax_error" class="text-danger">Error parsing line, check your syntax</span>
    </div>
  </form>
  <span class="lead" ng-show="error_msg==''">
    {{lockers.length}} lockers total</span>

  <span class="lead text-danger" ng-show="error_msg!=''">
    {{error_msg}}
  </span>
  <hr>

  
  <a type="button" ng-click="saveLockers()" class="btn btn-primary" ng-disabled="busy">Save Lockers</a>
  <a type="button" class="btn btn-default" href="<%=lockers_path%>">Cancel</a>
  
  <a type="button" class="btn btn-primary pull-right"
    href="<%=items_path%>">Locker Contents</a>
</div>

app/views/lockers/show.html.erb
<h2>Locker Details</h2>

<dl class="dl-horizontal">
  <dt>Number</dt><dd><%=@locker.number%></dd>
  <dt>Lock Serial</dt><dd><%=@locker.serial%></dd>
  <dt>Lock Combo</dt><dd><%=@locker.combo%></dd>
  <dt>Kit</dt><dd><%=@locker.kit%></dd>
  <dt>Notes</dt><dd><%=@locker.notes%></dd>
</dl>

<a type="button" class="btn btn-primary"
  href="<%=edit_locker_path(@locker)%>"><i class="icon-plus"></i> Edit Locker</a>

<a type="button" data-confirm="Are you sure?" data-method="delete"
   class="btn btn-danger" href="<%=locker_path(@locker)%>" rel="nofollow">
   Delete Locker</a>

<a href="<%=lockers_path%>" class="btn btn-default">Back</a>