config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  
  devise_for :users, :path=>"auth", :controllers=>{:registrations => :users}
  
  resources :users
  resources :grades, only: [:update, :edit, :show]
  resources :students do
    collection do
      post 'bulk_add'
      post 'bulk_remove'
    end
  end
  resources :assignments do
    member do
      get 'edit_grades'
      get 'update_grades'
      post 'save_grades'
    end
  end

  get 'admin/index' => 'admin#index'
  get 'reports/students' => 'reports#students'
  get 'reports/master' => 'reports#master'
  
  resources :lockers do
    collection do
      get 'checkout'
      post 'bulk_update'
      put 'rotate'
    end
  end
  
  resources :items

end

app/models/item.rb
class Item < ApplicationRecord

  validates :name, :presence => true
  validates :quantity, :presence=> true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :authenticate_user!
    
    before_action :set_item, only: [:show, :edit, :update, :destroy]
    
    respond_to :html
  
    def index
      @items = Item.all
      respond_with(@items)
    end
  
    def show
      respond_with(@item)
    end
  
    def new
      @item = Item.new
      respond_with(@item)
    end
  
    def edit
    end
  
    def create
      @item = Item.new(item_params)
      @item.save
      respond_with(@item)
    end
  
    def update
      @item.update(item_params)
      respond_with(@item)
    end
  
    def destroy
      @item.destroy
      respond_with(@item)
    end
  
    private
      def set_item
        @item = Item.find(params[:id])
      end
  
      def item_params
        params.require(:item).permit(:quantity, :name)
        
      end
  end
  

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% form_class="form-group"%>
  <% form_class+=" has-error" if @item.errors.include?(:quantity)%>
  <div class="<%=form_class%>">
    <%= f.label :quantity, :class=>"control-label"%>
    <%= f.text_field :quantity, :class=>"form-control"%>
  </div>
  <% form_class="form-group"%>
  <% form_class+=" has-error" if @item.errors.include?(:name)%>
  <div class="<%=form_class%>">
    <%= f.label :name, :class=>"control-label"%>
    <%= f.text_field :name, :class=>"form-control"%>
  </div>
  <div class="actions">
    <%= f.submit 'Save Item', :class=>"btn btn-primary" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h2>Editing item</h2>

<%= render 'form' %>
<%= link_to 'Back', items_path, :class=>"btn btn-default" %>

app/views/items/index.html.erb
<h2>Locker Contents</h2>
  <table class="table">
    <thead>
        <th>Item</th>
        <th>Quantity</th>
        <th></th>
    </thead>
    <tbody>
      <%@items.each do |item|%>
      <tr>
        <td>
          <%=item.name%>
        <td>
         <%=item.quantity%> 
        </td>
        <td>
          <a href="<%=item_path(item)%>"<i class="fa fa-edit"></i></a>
        </td>
      </tr>
      <%end%>
    </tbody>
  </table>
  <a type="button" class="btn btn-primary"
    href="<%=new_item_path%>"><i class="icon-plus"></i> Add Item</a>
 
  <a type="button" class="btn btn-default" href="<%=lockers_path%>">Back</a>
<table>
 

app/views/items/new.html.erb
<h2>New item</h2>

<%= render 'form' %>

<%= link_to 'Back', items_path, :class=>"btn btn-default" %>

app/views/items/show.html.erb
<h2>Item Details</h2>

<dl class="dl-horizontal">
  <dt>Name</dt><dd><%=@item.name%></dd>
  <dt>Quantity</dt><dd><%=@item.quantity%></dd>
</dl>

<a type="button" class="btn btn-primary"
  href="<%=edit_item_path(@item)%>"><i class="icon-plus"></i> Edit Item</a>

<a type="button" data-confirm="Are you sure?" data-method="delete"
   class="btn btn-danger" href="<%=item_path(@item)%>" rel="nofollow">
   Delete Item</a>

<a href="<%=items_path%>" class="btn btn-default">Back</a>